name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Code Checkout
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Code Review with SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0
        with:
          projectBaseDir: './'
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Bala-AZD_DevSec

      # Step 3: Docker Login
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Docker Build and Push
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Docker Container
        run: |
         docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
         docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
